### ISSUE TITLE
Crash on Android when returning from other activities

### ISSUE THREAD

**Issue by tjwoon** [Nexstream/cordova-plugin-eghl#1]
On a low end device, after switching to many other heavy applications, and then switching back to our app, the app will crash, with the following log:

```
D/CordovaInterfaceImpl( 3125): Sending activity result to plugin
D/eGHLPay ( 3125): onActivityResult: payment failure
D/AndroidRuntime( 3125): Shutting down VM
E/AndroidRuntime( 3125): FATAL EXCEPTION: main
E/AndroidRuntime( 3125): Process: my.com.tgv.app, PID: 3125
E/AndroidRuntime( 3125): java.lang.RuntimeException: Unable to resume activity {my.com.tgv.app/my.com.tgv.app.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=321, result=1, data=Intent { (has extras) }} to activity {my.com.tgv.app/my.com.tgv.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
E/AndroidRuntime( 3125): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3403)
E/AndroidRuntime( 3125): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3434)
E/AndroidRuntime( 3125): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772)
E/AndroidRuntime( 3125): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
E/AndroidRuntime( 3125): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
E/AndroidRuntime( 3125): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3125): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 3125): 	at android.app.ActivityThread.main(ActivityThread.java:5951)
E/AndroidRuntime( 3125): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3125): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3125): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
E/AndroidRuntime( 3125): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
E/AndroidRuntime( 3125): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=321, result=1, data=Intent { (has extras) }} to activity {my.com.tgv.app/my.com.tgv.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
E/AndroidRuntime( 3125): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4067)
E/AndroidRuntime( 3125): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3389)
E/AndroidRuntime( 3125): 	... 11 more
E/AndroidRuntime( 3125): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
E/AndroidRuntime( 3125): 	at my.com.nexstream.cordovaPlugins.eGHLPay.onActivityResult(eGHLPay.java:66)
E/AndroidRuntime( 3125): 	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:153)
E/AndroidRuntime( 3125): 	at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:348)
E/AndroidRuntime( 3125): 	at android.app.Activity.dispatchActivityResult(Activity.java:6549)
E/AndroidRuntime( 3125): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4063)
E/AndroidRuntime( 3125): 	... 12 more
```

Similar issues in other plugins:

- https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/365

See the following for methods to fix:

- https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html#launching-other-activities
- https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#lifecycle-guide

**Comment by tjwoon** [comment]
Fixed. See README for instructions on receiving plugin results if CordovaActivity is killed.
